### ISSUE TITLE
💡 Proposal to support other O/S arch binaries for release artefacts for Retina. ☕️🥷

### ISSUE THREAD

**Issue by Tatsinnit** [microsoft/retina#100]
### Support release artefacts for other distros.

* Please support release artefacts with other Operating System support For easy consumptions from other tools. Opening this as placeholder. thanks heaps.

**Describe the solution you'd like**

* [When the release artifcats are created.](https://github.com/microsoft/retina/releases/tag/v0.0.1) - It will be really helpful for other tools to consume this binary for other operating distress like windows, Darwin (Mac O/S) et. al.

**Additional context**

* Will be worth to include other archs in the artefacts like, currently it only support 1.

<img width="927" alt="Screenshot 2024-03-20 at 9 38 38 PM" src="https://github.com/microsoft/retina/assets/6233295/244234dd-0c70-4e55-97be-3a7c58ad3eff">

**Comment by rbtr** [comment]
We could build `kubectl-retina` for any Go platforms, but probably only targeting the same as `kubectl`? I'm evaluating the release process.
I would also like to distribute via `krew`, maybe I will open a separate tracking issue for that.
