### ISSUE TITLE
retina CLI version command shows only a blank line

### ISSUE THREAD

**Issue by k-nzw** [microsoft/retina#1013]
**Describe the bug**
Since `v0.0.17` release, `kubectl retina version` command shows only a blank line.

**To Reproduce**

1. Run `kubectl retina version`

**Expected behavior**
Version number should be displayed.

**Screenshots**
Until v0.0.16:
```
$ kubectl retina version
v0.0.16
```
Since v0.0.17:
```
$ kubectl retina version

```

**Platform (please complete the following information):**

- OS: Ubuntu 22.04, Windows
- Kubernetes Version: 1.29
- Host: self-host
- Retina Version: v0.0.17, v0.0.18

**Additional context**
PR #991 may have affected this.

**Comment by root-hbx** [comment]
Hi @k-nzw! I'm a little bit interested in this issue, can I have a try?

**Comment by timraymond** [comment]
@root-hbx Assigned! Thanks for taking this up! Let us know if you have any questions and feel free to stop by the weekly office hours.

**Comment by root-hbx** [comment]
> [@root-hbx](https://github.com/root-hbx) Assigned! Thanks for taking this up! Let us know if you have any questions and feel free to stop by the weekly office hours.

Thanks! Currently working on :)
