### ISSUE TITLE
Fix user guide since fetching latest version is failed

### ISSUE THREAD

**Issue by root-hbx** [microsoft/retina#1020]
**Describe the bug**

Latest `VERSION` is not up to date.

According to Release in this repo, [v0.10.1](https://github.com/microsoft/retina/releases/tag/v0.10.1) is the latest version.

But the fetched latest in CLI on local machine is still `v0.0.18`

**To Reproduce**

I was following guide in `README.md`, everything works well until: [metrics-quick-install](https://github.com/microsoft/retina?tab=readme-ov-file#metrics-quick-install-guide)

The problem is Latest `VERSION` is not up to date.

```sh
❯ VERSION=$( curl -sL https://api.github.com/repos/microsoft/retina/releases/latest | jq -r .name)
❯ echo $VERSION
v0.0.18
```

Obviously, it didn't automatically fetch the latest version.

**Expected behavior**

I bypass this issue with "hard-code":

```sh
❯ VERSION=v0.10.1
  ~                                                                                                                                                           ⎈ kind-skypilot  01:27:57
❯ helm upgrade --install retina oci://ghcr.io/microsoft/retina/charts/retina \
    --version $VERSION \
    --set image.tag=$VERSION \
    --set operator.tag=$VERSION \
    --set logLevel=info \
    --set enabledPlugin_linux=dropreason\\,packetforward\\,linuxutil\\,dns
Release "retina" does not exist. Installing it now.
Pulled: ghcr.io/microsoft/retina/charts/retina:v0.10.1
Digest: sha256:428fdcfc197b275cd41cf094b5bed4077b2eecad002a6ed31868e388ec7c42b3
NAME: retina
LAST DEPLOYED: Mon Nov 18 01:27:59 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Installing retina service using helm: helm install retina ./deploy/legacy/manifests/controller/helm/retina/ --namespace kube-system --dependency-update
2. Cleaning up/uninstalling/deleting retina and dependencies related:
  helm uninstall retina -n kube-system
```

Now it works.

**Platform (please complete the following information):**

- OS: Apple M2 Pro
- Kubernetes Version: 1.29.4
- Host: KIND
- Retina Version:

**Comment by nddq** [comment]
hey @root-hbx , `v0.0.18` is indeed Retina's latest version. I double checked that it is marked as `latest` on Github. The reason why we published `v0.10.1` is so that we can retracted `v0.10.0` which was mistakenly published. 
![Image](https://github.com/user-attachments/assets/184c6d25-103e-44b3-b632-87c011da879b)

**Comment by nddq** [comment]
@root-hbx Since `v0.10.1` and `v0.10.0` are retracted, if a user is running those versions and they run `go get github.com/microsoft/retina/@latest` to update to the latest version, it should fall back `v0.0.18`

**Comment by root-hbx** [comment]
@nddq Yes! Theoretically, it should return the `v0.0.18` package. However, in my test [above](https://github.com/microsoft/retina/issues/1020#issuecomment-2482447832), it produces an error instead. What could be the reason for this?

**Comment by TomHenning** [comment]
@nddq v0.10.1 is still the latest package of `charts/retina` (i.e. not retracted), and there still is no v0.18.0 available.
![Image](https://github.com/user-attachments/assets/5f831c28-983f-497d-87be-369f401e1db7)

**Comment by nddq** [comment]
@TomHenning looks like chart publishing is failing, I opened an issue to track it here https://github.com/microsoft/retina/issues/1081
