### ISSUE TITLE
 make helm-install (malformed module path "io/fs")

### ISSUE THREAD

**Issue by seilorjunior** [microsoft/retina#105]
**Describe the bug**
When i follow the setup of the installation for basic mode

**To Reproduce**
Clone the repo and run make helm-install

**Expected behavior**
No error to create the package of helm

**Screenshots**
![image](https://github.com/microsoft/retina/assets/13451867/c8c36ee2-042a-4762-9926-ae4deaf53a26)

**Platform (please complete the following information):**

- OS: Ubuntu
- Retina Version: the latest version of the repo

**Additional context**
The error
 seilor   retina   main ≡  ~2    make helm-install                                    ﳑ in bash at 11:31:08
cd crd && make manifests && make generate
make[1]: Entering directory '/home/seilor/retina/crd'
make[2]: Entering directory '/home/seilor/retina'
cd /home/seilor/retina/hack/tools; go mod download; go build -tags=tools -o bin/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
build sigs.k8s.io/controller-tools/cmd/controller-gen: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
make[2]: *** [Makefile:90: /home/seilor/retina/hack/tools/bin/controller-gen] Error 1
make[2]: Leaving directory '/home/seilor/retina'
make[1]: *** [Makefile:21: /home/seilor/retina/hack/tools/bin/controller-gen] Error 2
make[1]: Leaving directory '/home/seilor/retina/crd'
make: *** [Makefile:391: manifests] Error 2

**Comment by rbtr** [comment]
Hey @seilorjunior, I can't repro this. What version of Go are you using?

**Comment by seilorjunior** [comment]
> Hey @seilorjunior, I can't repro this. What version of Go are you using?

this one go version go1.13.8 linux/amd64

**Comment by rbtr** [comment]
> go1.13.8

that's quite outdated. can you update to at least go1.20 and try again?

**Comment by seilorjunior** [comment]
> make helm-install

Hello same error.
![image](https://github.com/microsoft/retina/assets/13451867/7e57f469-d303-4f22-af43-236afbb6ed22)

**Comment by seilorjunior** [comment]
> make helm-install

with sudo worked with the new version of go, maybe is good to add this on the docs :), because on ubunto with apt-get it installs a older version.

make helm-install
cd crd && make manifests && make generate
make[1]: Entering directory '/root/repos/retina/crd'
make[2]: Entering directory '/root/repos/retina'
cd /root/repos/retina/hack/tools; go mod download; go build -tags=tools -o bin/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
make[2]: Leaving directory '/root/repos/retina'
rm -rf /root/repos/retina/deploy/manifests/controller/helm/retina/crds
/root/repos/retina/hack/tools/bin/controller-gen crd paths="./api/..." output:crd:artifacts:config=/root/repos/retina/deploy/manifests/controller/helm/retina/crds
make[1]: Leaving directory '/root/repos/retina/crd'
make[1]: Entering directory '/root/repos/retina/crd'
/root/repos/retina/hack/tools/bin/controller-gen object paths="./api/..."
make[1]: Leaving directory '/root/repos/retina/crd'
helm upgrade --install retina ./deploy/manifests/controller/helm/retina/ \
        --namespace kube-system \
        --set image.repository=ghcr.io/microsoft/retina/retina-agent \
        --set image.initRepository=ghcr.io/microsoft/retina/retina-init \
        --set image.tag=v0.0.1 \
        --set operator.tag=v0.0.1 \
        --set image.pullPolicy=Always \
        --set logLevel=info \
        --set os.windows=true \
        --set operator.enabled=false \
        --set enabledPlugin_linux="\[dropreason\,packetforward\,linuxutil\,dns\]"

**Comment by seilorjunior** [comment]
Needs to use go1.20 and not use sudo on the make command.
