### ISSUE TITLE
remove interface label for interface_stats

### ISSUE THREAD

**Issue by huntergregory** [microsoft/retina#1067]
To reduce metric cardinality, we should aggregate interfaces for `interface_stats`. We filter out several interfaces, and only error/drop stats are included, which are unlikely, but technically, there is risk that the number of interface names could increase over time.

Before:
```
interface_stats{interface=eth0, stat=...}
```

After:
```
interface_stats{stat=...}
```

**Comment by anubhabMajumdar** [comment]
Since this metric has been out for sometime, should we keep the `interface` label and set that to a constant value like `allInterfaces` ? Otherwise we may break existing tooling that interfaces with this metric (like Grafana dashboards).
