### ISSUE TITLE
capture pod failed with InvalidImageName error.

### ISSUE THREAD

**Issue by jacobbaek** [microsoft/retina#1110]
**Describe the bug**
capture create command succeed.
```
$ kubectl retina capture create  -n default --name example-blob --pod-selectors app=nginx-sample
```

but job failed with InvalidImageName.
```
Events:
  Type     Reason         Age               From               Message
  ----     ------         ----              ----               -------
  Normal   Scheduled      60s               default-scheduler  Successfully assigned default/example-blob-rjkwq-clcjr to aks-nodepool1-22198413-vmss000000
  Warning  InspectFailed  4s (x6 over 59s)  kubelet            Failed to apply default image tag "ghcr.io/microsoft/retina/retina-agent:": couldn't parse image name "ghcr.io/microsoft/retina/retina
-agent:": invalid reference format
  Warning  Failed         4s (x6 over 59s)  kubelet            Error: InvalidImageName
```

**To Reproduce**

1. install retina using kubectl krew
2. run 'kubectl retina capture create ~~~'
3. suceed to run `kubectl retina capture create ~~~` command
4. see InvalidImageName error when check the pod that is in job.

**Expected behavior**
pod deploying works fine.

**Screenshots**

**Platform (please complete the following information):**

- OS: Ubuntu 22.04
- Kubernetes Version: 1.30.6
- Host: AKS
- Retina Version: v0.0.20

**Additional context**
I tried to run below command and got the empty output.
```
$ kubectl retina version
<empty>
```
I think the empty value of [buildinfo.Version](https://github.com/microsoft/retina/blob/234edc50f33ecf3256dc7cfc3c788b78ee249276/cli/cmd/capture/create.go#L363C40-L363C47) is related this issue. 

The problem occurred from v0.0.17.
It works well using v0.0.16.

**Comment by nddq** [comment]
@jacobbaek this is due to a bug in our goreleaser pipeline, where the kubectl-retina was not built properly with `ldflags`. We merged this fix yesterday https://github.com/microsoft/retina/pull/1108, which the goreleaser pipeline will be trigger on the next release and hopefully solve the issue

**Comment by jacobbaek** [comment]
@nddq  Thanks for quick response.
I will wait for next release.

**Comment by jacobbaek** [comment]
I tested it using v0.0.21. it works well.
Thanks @nddq 
I will close this issue.
