### ISSUE TITLE
can't build binary by make install-kubectl-retina no rule to make target

### ISSUE THREAD

**Issue by avwsolutions** [microsoft/retina#131]
**Describe the bug**
Can't build binary as described in the [documentation](https://retina.sh/docs/installation/cli). Seems missing in Makefile make install-kubectl-retina

**To Reproduce**

git clone https://github.com/microsoft/retina.git
make install-kubectl-retina

make: *** No rule to make target 'install-kubectl-retina'.  Stop

**Expected behavior**
Should build the main repo binary.

**Platform (please complete the following information):**

- OS: Linux 
- Kubernetes Version: 1.29
- Host:  Cloud Shell (Bash)
- Retina Version: Latest (main)

**Comment by rbtr** [comment]
Hey @avwsolutions thanks for the report. This is my fault, the explicit kubectl-retina Make targets were removed here  - https://github.com/microsoft/retina/pull/112/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L180

You can build that binary with `goreleaser` now, something like `goreleaser build --snapshot --clean`. The goreleaser docs may explain in more detail how to build only specific platforms and other options. 
Feel free to PR an update to the docs and we'll get it updated before a 0.0.2 release!

**Comment by avwsolutions** [comment]
ok that's great. Already thought something like that. I will create a PR coming days.
