### ISSUE TITLE
Sign container images

### ISSUE THREAD

**Issue by rbtr** [microsoft/retina#141]
**Is your feature request related to a problem? Please describe.**
Images pushed to GHCR are not signed.

**Describe the solution you'd like**
Images pushed to GHCR should be signed to verify integrity and establish chain of trust.

**Additional context**
GitHub recommends https://github.com/sigstore/cosign-installer
per https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/
so this does not seem like it would be very complicated to enable.
Open to alternatives from anyone with experience signing images in GHA.

**Comment by rbtr** [comment]
sigstore (cosign?) can also be used to sign the OCI helm chart
https://helm.sh/docs/topics/registries/#using-sigstore-to-sign-oci-based-charts

**Comment by hainenber** [comment]
I made a PR to address this one. Please help assign and review if possible. Thanks!

**Comment by rbtr** [comment]
assigned you this issue
