### ISSUE TITLE
`make helm-install` does not install the latest image 

### ISSUE THREAD

**Issue by parkjeongryul** [microsoft/retina#163]
**Describe the bug**

The latest release is currently v0.0.2, but`make helm-install` with v0.0.2 code will install v0.0.1 image.

**To Reproduce**

```
$ git clone https://github.com/microsoft/retina.git
$ make helm-install
$ k get ds -n kube-system retina-agent -o yaml | grep image:
        image: ghcr.io/microsoft/retina/retina-agent:v0.0.1
      - image: ghcr.io/microsoft/retina/retina-init:v0.0.1
```

**Expected behavior**

Install latest image of current repo.

**Screenshots**

**Platform (please complete the following information):**

I don't think this information is needed for this issue.

**Additional context**

**Comment by rbtr** [comment]
thanks for the report, this is fixed by https://github.com/microsoft/retina/pull/142 which will also update the documentation to recommend the OCI helm install rather than the Make targets

**Comment by parkjeongryul** [comment]
> thanks for the report, this is fixed by https://github.com/microsoft/retina/pull/142 which will also update the documentation to recommend the OCI helm install rather than the Make targets

I see it was a known issue, thanks for sharing.
