### ISSUE TITLE
issues with published kubectl-retina binary

### ISSUE THREAD

**Issue by peterj** [microsoft/retina#181]
**Describe the bug**
With the https://github.com/microsoft/retina/releases/download/v0.0.2/kubectl-retina-darwin-arm64-v0.0.2.tar.gz binary, the `kubectl-retina version` command returns "undefined".

This doesn't happen if I run the CLI directly from the branch (e.g. `go run`).

It also might be related to the fact that when running `kubectl-retina capture`, the created job uses an incorrect image (`undefined` tag). E.g. `ghcr.io/microsoft/retina/retina-agent:undefined`

**Comment by rbtr** [comment]
fixed in #170, will be publish in v0.0.3

**Comment by rbtr** [comment]
@peterj btw we appreciate you hosting that exploration and filing the issues you encountered!
