### ISSUE TITLE
Investigate and optimize slow Windows CodeQL runs

### ISSUE THREAD

**Issue by rbtr** [microsoft/retina#200]
Windows CodeQL runs [take almost 10x longer](https://github.com/microsoft/retina/actions/runs/8497015180/job/23279467083) than the Linux variant and are the biggest chunk of CI time by far. 
Why? Can this be improved?

**Comment by 4rivappa** [comment]
Yeah CodeQL is taking up so much time for execution in windows, I went through the workflow. These are the things, I found.

The hotspot for this entire workflow is the step `Autobuild`. This step executes the yaml file of [codeql-action/autobuild](https://github.com/github/codeql-action/blob/main/autobuild/action.yml), and this is trying to build the code automatically. And below is the breakdown of the time taken for parts of autobuild step.

```
Linux Execution Autobuild (6m 33sec)      |  Windows Execution Autobuild (56m 29sec)
-------------------------------------------------------------------------------------
First Package (download modules)          |  First Package (download modules)
                                          |  
2024/03/31 15:05:52                       |  2024/03/31 15:06:36
2024/03/31 15:06:07                       |  2024/03/31 15:12:48
                                          |  
Time Taken: 00:00:15                      |  Time Taken: 00:06:12
                                          |  
---                                       |  ---
Running Extractor command                 |  Running Extractor command
                                          |  
2024/03/31 15:06:12                       |  2024/03/31 15:12:56
2024/03/31 15:12:10                       |  2024/03/31 16:00:36
                                          |  
Time Taken: 00:05:58                      |  Time Taken: 00:47:40
                                          |  
---                                       |  ---
Second Package (download modules)         |  Second Package (download modules)
                                          |  
2024/03/31 15:12:10                       |  2024/03/31 16:00:36
2024/03/31 15:12:22                       |  2024/03/31 16:02:55
                                          |  
Time Taken: 00:00:12                      |  Time Taken: 00:02:19
```
I hope this helps anyone, who will be picking up this issue.
Thanks :)

**Comment by rbtr** [comment]
Thanks for looking in to this @4rivappa 🙂 
I guess the next step is for someone to figure out why Windows `Extractor` is taking so long

**Comment by rbtr** [comment]
I had an idea to make Windows CodeQL faster - [don't run it on Windows](https://github.com/rbtr/retina/commit/715f6bda20c7c164641d165c6d42a60b6bbec3db#diff-ec82a1210eee62532fa878b35c0defd6db76f03a97579afabe79a90588d72165R19).
I set GOOS=windows but run the Job on an Ubuntu runner.
Is it faster? Yes.
Does it actually analyze Windows? I'm not sure.

[Here's the link to the CodeQL run.](https://github.com/rbtr/retina/actions/runs/8528914682)
I'm encouraged that it says it scanned a different number of files, but the math still doesn't add up to the number of files on either platform that I would expect.

**Comment by rbtr** [comment]
I would love to hear from a CodeQL expert (or anyone willing to investigate this further) but in the meantime I think #212 may resolve this
