### ISSUE TITLE
Most or all metrics exported by Retina should be counters, not gauges

### ISSUE THREAD

**Issue by andreev-io** [microsoft/retina#237]
**Describe the bug**
Retina is currently exporting gauge-type metrics in its modules (e.g. [forward.go](https://github.com/microsoft/retina/blob/main/pkg/module/metrics/forward.go#L30), [drops.go](https://github.com/microsoft/retina/blob/main/pkg/module/metrics/drops.go). Since these metrics only go up (or are reset to 0), they should be counters. This is important since a metric type different from the metric's semantical meaning can break the implicit contract and assumptions that people make when querying the data.

From [Prometheus documentation](https://prometheus.io/docs/concepts/metric_types/):

> A gauge is a metric that represents a single numerical value that can arbitrarily go up and down.

> A counter is a cumulative metric that represents a single [monotonically increasing counter](https://en.wikipedia.org/wiki/Monotonic_function) whose value can only increase or be reset to zero on restart. For example, you can use a counter to represent the number of requests served, tasks completed, or errors.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Platform (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by andreev-io** [comment]
I'm going to open a PR to address this in the `forward` plugin as an example.

**Comment by andreev-io** [comment]
@rbtr Could you assign this to me? I opened https://github.com/microsoft/retina/pull/238, but I need some help with figuring out how to build Retina locally: https://github.com/microsoft/retina/pull/238#issuecomment-2042712405.

**Comment by nddq** [comment]
just look at these metrics recently and thought of this issue. The reason why we are doing gauges and not counters, even though these metrics _supposed_ to be only ever increasing, is that because we are doing snapshots of the bpf map periodically and `Set` the metric to whatever the values we've read. The actual counting is being done in eBPF. We should rename `<MetricName>Counter` to `<MetricName>Gauge` to prevent confusion
