### ISSUE TITLE
Feature Request: Outputting the .tar FileName as part of Retina Output please. ☕️

### ISSUE THREAD

**Issue by Tatsinnit** [microsoft/retina#286]
**Is your feature request related to a problem? Please describe.**

Can we please get the actual filename printed once Retina CLI distributed Capture command ran successfully. cc: @rbtr and @vakalapa ☕️💡

Issue this will resolve is to the consuming tools which can then use the output and use Kubectl copy to specifically only copy that file to local machine.

So say for example if I have retina run if I get presented with the specific filename I can parse the output and only copy that tar from the node to local host. 

<img width="658" alt="Screenshot 2024-04-17 at 9 31 05 PM" src="https://github.com/microsoft/retina/assets/6233295/975784ea-2c91-4f6d-8399-83c17bdf0813">

**Describe the solution you'd like**

Can we please get the actual filename printed once Retina CLI distributed Capture command ran successfully.

**Describe alternatives you've considered**

Alternatively for now I just copy the whole of Capture folder from node to locally, as I presume this tool will not be used beyond diagnostics reasons.

**Additional context**

**Comment by rbtr** [comment]
The challenge here is that the timestamp that is appended to the capture name is generated by the capture Job while it is running on the Node itself. So, the CLI doesn't know what that suffix is going to be, especially if you execute it with `--no-wait`.
The rest of the name is discoverable, it's `Capture Name - Node Name - (?Timestamp?) .tar.gz`.

I think sticking the timestamp on the end of a network capture is pretty standard for this kind of tool where you might be running it over and over and collecting data over time, and I think we should keep that. But maybe the timestamp could be generated by the CLI and passed in to the Job? This means the CLI knows what the tgz filenames will be, and also that they are predictable/consistent across all the Nodes? 

There is a minor semantic shift in that the timestamp is the time of request of the capture, and not the true start time of the capture, but the slip should be small...as long as we document those semantics clearly I think it's okay.

**Comment by Tatsinnit** [comment]
> The challenge here is that the timestamp that is appended to the capture name is [generated by the capture Job](https://github.com/microsoft/retina/blob/96d42f9e6439ed6d12821ef416983df5165ccbb1/pkg/capture/provider/network_capture_common.go#L23) while it is running on the Node itself. So, the CLI doesn't know what that suffix is going to be, especially if you execute it with `--no-wait`. The rest of the name is discoverable, it's `Capture Name - Node Name - (?Timestamp?) .tar.gz`.
> 
> I think sticking the timestamp on the end of a network capture is pretty standard for this kind of tool where you might be running it over and over and collecting data over time, and I think we should keep that. But maybe the timestamp could be generated by the CLI and passed in to the Job? This means the CLI knows what the tgz filenames will be, and also that they are predictable/consistent across all the Nodes?
> 
> There is a minor semantic shift in that the timestamp is the time of request of the capture, and not the true start time of the capture, but the slip should be small...as long as we document those semantics clearly I think it's okay.

Awesome!! @rbtr ☕️🙏 thank you for this detail comment. I am not sure if this is targeted to me, but sharing just 2 cents: 💡💡

* I really like your suggestion/idea because that way CLI can send upfront the name of file which will help greatly (don't know how much the work it will be). You are absolutely bang on money about the challenge with the exactness of [`(?Timestamp?) .tar.gz`](https://github.com/microsoft/retina/blob/96d42f9e6439ed6d12821ef416983df5165ccbb1/pkg/capture/provider/network_capture_common.go#L23) is unpredictable so anything which makes it bit easy to locate.

* As a minor suggestion/idea: We could also supply custom filenames flag `--node-filename` and with that flag its responsibility oof user / consuming tool to name uniquely otherwise it will over-write the previous file name.

Thank you so much for this. Really appreciate it, sorry if this was target to wider other audience.

**Comment by spencermckee** [comment]
@Tatsinnit Thanks for the feedback. We can add the capture names to the CLI logs and they can be parsed from there. `kubectl cp` can be used to rename the file so you can customize the filename at that point. Would that work for your use case?

**Comment by Tatsinnit** [comment]
> @Tatsinnit Thanks for the feedback. We can add the capture names to the CLI logs and they can be parsed from there. `kubectl cp` can be used to rename the files so you can customize the filenames at that point. Would that work for your use case?

Thanks @spencermckee for loop back. Cool, just to add more clarity, you mean the `filename` will be part of the command run output aka CLI log so we can parse it from there? Happy to chat more. Thank you.

**Comment by spencermckee** [comment]
@Tatsinnit Yes, sounds like we're on the same page.

**Comment by kamilprz** [comment]
Hey @Tatsinnit , been a while since you created the issue, but I was assigned to work on it recently.

I have made a PR here https://github.com/microsoft/retina/pull/894 , please feel free to review and give your thoughts!
