### ISSUE TITLE
log: fix "unsupported value" error in a log line

### ISSUE THREAD

**Issue by huntergregory** [microsoft/retina#309]
`zap.Any()` does not support the field passed at [packetparser/packetparser_linux.go:217](https://github.com/microsoft/retina/blob/02d7179f922539f1682ca295af0d9fc7324d63bb/pkg/plugin/packetparser/packetparser_linux.go#L217C42-L217C83)

We should find another way to log the `eth0Link`:
```
level=info caller=packetparser/packetparser_linux.go:217 msg="Attaching Packetparser to eth0" goversion=go1.21.9 os=linux arch=amd64 numcores=4 hostname=aks-nodepool1-17703939-vmss000000 podname=retina-agent-cqnxv version=b8538dc apiserver=https://vakr-04-16-vakr-04-16-9b8218-ezit2obj.hcp.westus2.azmk8s.io:443 plugins=linuxutil,packetforward,packetparser,dns,dropreason eth0Link= eth0LinkError="unsupported value type"
```

**Comment by roopeshsn** [comment]
> `zap.Any()` does not support the field passed at [packetparser/packetparser_linux.go:217](https://github.com/microsoft/retina/blob/02d7179f922539f1682ca295af0d9fc7324d63bb/pkg/plugin/packetparser/packetparser_linux.go#L217C42-L217C83)
> 
> We should find another way to log the `eth0Link`:
> 
> ```
> level=info caller=packetparser/packetparser_linux.go:217 msg="Attaching Packetparser to eth0" goversion=go1.21.9 os=linux arch=amd64 numcores=4 hostname=aks-nodepool1-17703939-vmss000000 podname=retina-agent-cqnxv version=b8538dc apiserver=https://vakr-04-16-vakr-04-16-9b8218-ezit2obj.hcp.westus2.azmk8s.io:443 plugins=linuxutil,packetforward,packetparser,dns,dropreason eth0Link= eth0LinkError="unsupported value type"
> ```

It's a netlink.Link interface right?

**Comment by timraymond** [comment]
@huntergregory is this still an issue? It seems like the offending log line has been changed to remove `zap.Any` entirely...

**Comment by mereta** [comment]
@ibezrukavyi this one seem to eb outdated. Closing.
