### ISSUE TITLE
ideally agent's init container enables telemetry based on ConfigMap flag

### ISSUE THREAD

**Issue by huntergregory** [microsoft/retina#339]
If an `ApplicationInsightsID` is set at image build time, then the retina-agent-init container seems to enable telemetry here:
https://github.com/microsoft/retina/blob/6946babd353e3afae17a5a054209b7af3e8933bf/init/retina/main_linux.go#L26-L33

Instead, it should enable telemetry if `ApplicationInsightsID` is set AND `enableTelemetry` is true:
https://github.com/microsoft/retina/blob/6946babd353e3afae17a5a054209b7af3e8933bf/deploy/manifests/controller/helm/retina/templates/configmap.yaml#L19

**Comment by Carpe-Wang** [comment]
Would I handle this issue?
