### ISSUE TITLE
bug: Update LLVM version in contributing doc

### ISSUE THREAD

**Issue by anubhabMajumdar** [microsoft/retina#425]
Ref: https://github.com/microsoft/retina/blob/9f455ca581af8b5355386d55ed0a70e2ee86ef20/docs/contributing/developing.md?plain=1#L14

Need LLVM version 16 for local compilation.

**Comment by 4rivappa** [comment]
shall I make a PR for this refactor ?

**Comment by rbtr** [comment]
@4rivappa please feel free, assigning it to you
