### ISSUE TITLE
Dashboard tests are not running

### ISSUE THREAD

**Issue by huntergregory** [microsoft/retina#501]
Tests are not running to check that dashboards are simplified (tests introduced in #264).

We can copy simplify-grafana.go and other go files to deploy/hubble/grafana/

The test checks files running in the current directory “./“. It should also try files in the “./deploy/hubble/grafana/“ and “./legacy/deploy/grafana/“ directory (if directory does not exist, do not fail the test).

If no JSON files are found, the test should fail.

**Comment by whatnick** [comment]
I am happy to take this on, please assign me.

**Comment by timraymond** [comment]
@whatnick Done! Thanks for taking it on.
