### ISSUE TITLE
Errors when using ExternalName or Headless services

### ISSUE THREAD

**Issue by cmergenthaler** [microsoft/retina#547]
**Describe the bug**
Retina agents log a lot of error messages when having headless service in the cluster or of type ExternalName.

``` log
updateSvc: error getting primary IP for service
no primary IP found for service myService
```

**To Reproduce**

1. Deploy externalname or headless service to the cluster
2. Observe agent logs

**Expected behavior**
Retina should just ignore those services (or use endpoint ips of headless service?)

**Platform (please complete the following information):**

- OS: AzureLinux
- Kubernetes Version: 1.19
- Host: AKS
- Retina Version: 0.0.12

**Additional Information:**
I guess the relevant code is this, where it tries to save ClusterIP, even though not all services is k8s have a ClusterIP

https://github.com/microsoft/retina/blob/b71ec003ad1bb313524ea30e6fc8368c4ce249ab/pkg/controllers/daemon/service/controller.go#L78

https://github.com/microsoft/retina/blob/b71ec003ad1bb313524ea30e6fc8368c4ce249ab/pkg/common/service.go#L46

**Comment by whatnick** [comment]
Confirmed this as an issue with our Headless services as well.
