### ISSUE TITLE
[hubble control plane] flows are not being enriched

### ISSUE THREAD

**Issue by huntergregory** [microsoft/retina#599]
We would like flows to include Pod namespace/name, but I'm only seeing IPs when installing agent with `make helm-install-without-tls`.

Version: v0.0.14 (also building off of main)

![image](https://github.com/user-attachments/assets/e7fda050-7339-4373-944d-6647229ec18d)

For instance, the highlighted IPs in the image correspond to real Pods:
```shell
$ k get po -n default -owide
NAME                             READY   STATUS    RESTARTS   AGE     IP             NODE                                NOMINATED NODE   READINESS GATES
kapinger-bad-7778f55bf8-657f9    1/1     Running   0          4h11m   10.224.1.211   aks-nodepool1-32351195-vmss000001   <none>           <none>
kapinger-good-8468b88556-2l9b9   1/1     Running   0          4h16m   10.224.0.155   aks-nodepool1-32351195-vmss000000   <none>           <none>
```

Retina agent and operator are running fine, and Cilium endpoints/identities look fine.

**Comment by nddq** [comment]
might be related/duplicated of this https://github.com/microsoft/retina/issues/536

**Comment by huntergregory** [comment]
Closing this duplicate issue
