### ISSUE TITLE
Enable Service monitor based linkage to Prometheus 

### ISSUE THREAD

**Issue by whatnick** [microsoft/retina#649]
**Is your feature request related to a problem? Please describe.**
The pod annotations based scraping of Metrics from retina daemonset pods to Prometheus is unreliable / being deprecated.

**Describe the solution you'd like**
Provide Service monitor templates in future helm charts to link Retina to Prometheus.

**Describe alternatives you've considered**
Configuring kube-prometheus-stack to scrape from annotated pods.

**Additional context**

**Comment by SRodi** [comment]
it seems https://github.com/microsoft/retina/pull/695 relates to this issue

**Comment by SRodi** [comment]
@whatnick could you please clarify if #695 already addresses this issue, or whether anything else is required in order to close this off? Thanks.

**Comment by whatnick** [comment]
This is fixed for legacy charts and cand be closed.
