### ISSUE TITLE
Wrong latest version of package when running `go mod tidy`

### ISSUE THREAD

**Issue by alexcastilio** [microsoft/retina#714]
**Describe the bug**
I tried to import github.com/microsoft/retina in my go code and when I ran `go mod tidy`, I got latest version (v0.10.0) which is not right, since latest is v0.0.16

**To Reproduce**
create a go package
import `github.com/microsoft/retina`
run `go mod tidy`
check go.mod: `require github.com/microsoft/retina v0.10.0`

**Expected behavior**
After run `go mod tidy`, check go.mod: `require github.com/microsoft/retina v0.0.16`

**Screenshots**
Screenshot of [pkg.go.dev](https://pkg.go.dev/github.com/microsoft/retina@v0.10.0?tab=versions) where latest version is also shown as v0.10.0: 
![image](https://github.com/user-attachments/assets/866f0105-ac41-42cd-9b4e-1f5caa4421cf)

**Platform (please complete the following information):**

- OS: [e.g. AzureLinux]
- Kubernetes Version: [e.g. 1.22]
- Host: [e.g. AKS, KIND, self-host, etc]
- Retina Version:

**Additional context**

**Comment by rbtr** [comment]
https://pkg.go.dev/about#removing-a-package
maybe we can fix this? @kamilprz @alexcastilio
