### ISSUE TITLE
Helm installation does not reflect helm's --namespace argument, but hardcodes kube-system (or rather hides it in the values.yaml)

### ISSUE THREAD

**Issue by kastl-ars** [microsoft/retina#731]
**Describe the bug**
Normally one can install a helm release into a discrete namespace by using `helm install --namespace foo ...`.

This does not work with the retina chart, as it puts the helm release into that namespace, but the resources into the `kube-system` namespace.

e.g. https://github.com/microsoft/retina/blob/main/deploy/legacy/manifests/controller/helm/retina/values.yaml#L47

If there is a technical reason for doing so, this should be documented. If not, this should be fixed to get the usual behaviour.

**To Reproduce**

1. Install using the following command:

```
helm upgrade --install retina oci://ghcr.io/microsoft/retina/charts/retina \
    --namespace retina \
    --create-namespace \
    --version $VERSION \
    --namespace kube-system \
    --set image.tag=$VERSION \
    --set operator.tag=$VERSION \
    --set logLevel=info \
    --set enabledPlugin_linux="\[dropreason\,packetforward\,linuxutil\,dns\]"
```

3. Issue `helm ls -n retina` and find the release there, but no pods or daemonsets (as `kubectl get pod,ds -n retina` shows)
4. Check for daemonsets in the `kube-system` namespace using `kubectl get pod,ds -n kube-system`
5. Voilá!

**Expected behavior**
The chart should respect helm's `--namespace` argument

**Platform (please complete the following information):**

- OS: openSUSE Leap 15.6
- Kubernetes Version: v1.30.4+k3s1
- Host: self-hosted VM
- Retina Version: 0.0.16

**Comment by kastl-ars** [comment]
In addition, the operator daemonset always gets deploy to `kube-system`, even if its configMap is created in e.g. the `retina` namespace.

https://github.com/microsoft/retina/blob/main/deploy/legacy/manifests/controller/helm/retina/templates/operator.yaml#L6

**Comment by BeegiiK** [comment]
@kastl-ars 

Thank you for creating an issue. During my investigation, there's two things to mention:
* The operator was always going to get deployed to `kube-system`. Now the daemonset can get deployed in any namepsace provided by the user.
* The commands you provided needs to be updated. The `--namespace` option will get overrided if the namespace chart value exists (which in this case does) and that is why you'll never see it deployed elsewhere. You'll need to use the `--set namespace=X` option instead. I've tested this and it works!
