### ISSUE TITLE
[Docs] Missing "kubectl" in command

### ISSUE THREAD

**Issue by kastl-ars** [microsoft/retina#733]
https://github.com/microsoft/retina/blob/735192eb444bcf4413019c4fe68378b43e30299f/docs/04-Captures/cli.md?plain=1#L9

This should read `kubectl retina capture...`.

**Comment by rbtr** [comment]
The Retina CLI can be invoked directly, it does not _need_ to be `kubectl` plugin, so this would actually work. It is a bit confusing that all of the subsequent examples in this page invoke it as a plugin though. This should be explained and made consistent.

**Comment by kastl-ars** [comment]
Yes, it should be unified to make it consistent.

And: When I download the tarball from the release, there is only a `kubectl-retina` binary in it, without further instructions. Moving that to a directory in my PATH means I can call `kubectl retina ...`, but not `retina` directly.

As this is the only command without `kubectl`, I would propose to stick to the usage with `kubectl retina ...`.
