### ISSUE TITLE
remove irrelevant metric labels for dns and apiserver latency

### ISSUE THREAD

**Issue by vakalapa** [microsoft/retina#75]
If my understanding is correct, these labels seem irrelevant to these metrics.

## DNS
Seems like DNS request doesn't need `num_response`, `response`, or `return_code`.

```
networkobservability_dns_request_count{num_response="0",query="wpad.svc.cluster.local.",query_type="A",response="",return_code=""} 354
```

## API Server Latency

Remove `count` label from `adv_node_apiserver_no_response`. Only possible time series for this metric right now is:
```
adv_node_apiserver_no_response{count="no_response"}
```

See _latency.go_

**Comment by iamrajhans** [comment]
@vakalapa can I take this

**Comment by vakalapa** [comment]
Sure assigning this to you. Ease feel free to ask any questions you might have.
