### ISSUE TITLE
duplicate windows metric: remove `windows_hns_stats`, keep `forward_count`

### ISSUE THREAD

**Issue by vakalapa** [microsoft/retina#92]
**Describe the bug**
`networkobservability_windows_hns_stats` is a copy of `networkobservability_forward_count`:
https://github.com/microsoft/retina/blob/078d15b3612dc2abacd77b01dc9e6413dd3dbb2a/pkg/plugin/windows/hnsstats/hnsstats_windows.go#L145
```
# HELP networkobservability_forward_count Total forwarded packets
# TYPE networkobservability_forward_count gauge
networkobservability_forward_count{direction="egress"} 176730
networkobservability_forward_count{direction="ingress"} 520660
# HELP networkobservability_windows_hns_stats Include many different metrics from packets sent/received to closed connections
# TYPE networkobservability_windows_hns_stats gauge
networkobservability_windows_hns_stats{direction="win_packets_recv_count"} 520660
networkobservability_windows_hns_stats{direction="win_packets_sent_count"} 176730
```

**Comment by iamrajhans** [comment]
@vakalapa just wanted to confirm here the below metrics need to be removed, correct?
https://github.com/microsoft/retina/blob/078d15b3612dc2abacd77b01dc9e6413dd3dbb2a/pkg/plugin/windows/hnsstats/hnsstats_windows.go#L142-L149

**Comment by vakalapa** [comment]
@iamrajhans yes, thanks for looking into this. We will need to verify if the hnscounter stats are being used in the usual forward metrics (both bytes and packet counts) if yes, we are free to delete the duplicate metrics. If not we have to count them in forward metrics.

**Comment by spencermckee** [comment]
@vakalapa Do you mean the hns counter stats need to be counted in the forward bytes and packet counts? It looks like this is already the case. The top and bottom lines here show the `ForwardCounter` and `WindowsCounter` are both being set to the hns `packetsReceived` and `packetsSent`.

https://github.com/microsoft/retina/blob/078d15b3612dc2abacd77b01dc9e6413dd3dbb2a/pkg/plugin/windows/hnsstats/hnsstats_windows.go#L136-L149

**Comment by vakalapa** [comment]
@spencermckee  yeah looks like they are double counted as a duplicate metrics, we should remove `networkobservability_windows_hns_*` metrics and make sure all the data is counted in only `networkobservability_forward_*` metrics.
