### ISSUE TITLE
Refactor usages of `unsafe`

### ISSUE THREAD

**Issue by rbtr** [microsoft/retina#95]
There are usages of unsafe which could be made safe
https://github.com/microsoft/retina/blob/078d15b3612dc2abacd77b01dc9e6413dd3dbb2a/pkg/utils/utils_linux.go#L41

may be refactored as
```go
func htons(i uint16) uint16 {
  b := make([]byte, 2)
  binary.BigEndian.PutUint16(b, i)
  return binary.BigEndian.Uint16(b)
}
```

**Comment by Troy-Butler** [comment]
Hi, could you please assign this issue to me?

**Comment by vakalapa** [comment]
@Troy-Butler Assigned the issue to you.
