### ISSUE TITLE
Using NPM vs Yarn to build docs

### ISSUE THREAD

**Issue by kamilprz** [microsoft/retina#988]
Within `site/README.md` it is mentioned to use Yarn for building docs locally, however, the make file uses npm.

In the project we have a `package-lock.json` which indicates that this project uses npm and ensures consistent installs across different environments. Yarn uses `yarn.lock` instead. Using both locks can lead to conflicts if they are out-of-sync.

We should remain consistent. Suggested change would be to remove the Yarn documentation.

**Comment by timraymond** [comment]
Agree that having both is a problem, but I'm surprised at the suggestion. I thought Yarn was better for many reasons (reproducibility, speed).
